pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    arguments: --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config  

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: CitizenEnforcer-artifacts
