pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    publishWebProjects: false
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config 
    zipAfterPublish: true    

- task: PublishBuildArtifacts@1
